### ISSUE TITLE
Update to r70

### ISSUE THREAD

**Issue by jtreml** [toruta39/threejs-dash-gen#5]
Any chance you could update this to the latest r70 version? I tried to do it myself but can't get your script to run without errors.

**Comment by toruta39** [comment]
@jtreml Thanks for reminding. I'll update it ASAP.

**Comment by toruta39** [comment]
@jtreml It looks like the phantomjs error output is caused by the newly added material browser iframes in the material related docs, which is ignorable if you don't care about the material browser.
I'll make the material browser supported by this weekend.

**Comment by toruta39** [comment]
Update done

**Comment by jtreml** [comment]
That was fast! Thank you!
